In [3]:
import tensorflow as tf

In [9]:
sess = tf.InteractiveSession()
a = tf.one_hot([[0],[1],[2],[3]],depth=4).eval()

In [ ]:
tf.cast([1.3,3,9,3,])

tf.reduce_mean(tf.cast([True, False, 1==1, 1!=1], tf.float32)).eval()

In [22]:
x= [1.4]
y= [2,5]
z= [3,6]

tf.stack([x,y,z]).eval()

TypeError: Tensors in list passed to 'values' of 'Pack' Op have types [float32, int32, int32] that don't all match.

In [11]:
x = [[1,2,3],[4,5,6],[7,8,9]]
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# numpy 잠깐

In [12]:
import numpy as np

In [19]:
x = np.array([[1,2,3],[4,5,6]])
print(x.shape)
print(np.ndim(x))

(2, 3)
2


In [25]:
a = np.zeros((10,10))
print(a)
b = np.ones((10,10))
print(b)
c= np.full((10,10),7)
print(c)
d= np.eye(3)
print(d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
print(np.random.random((3,3))) #랜덤값 넣어주기
print(np.linspace(0,20,20)) #0부터 20까지 균일하게 20등분해서 나타남 -> 그래프 그릴때 스무스하게 나타낼수있다

[[0.40453571 0.23029199 0.24250822]
 [0.03880201 0.56718108 0.25664616]
 [0.63623276 0.48906606 0.51155942]]
[ 0.          1.05263158  2.10526316  3.15789474  4.21052632  5.26315789
  6.31578947  7.36842105  8.42105263  9.47368421 10.52631579 11.57894737
 12.63157895 13.68421053 14.73684211 15.78947368 16.84210526 17.89473684
 18.94736842 20.        ]


In [41]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
x[:2, 1:]
y = x[:] # deepcopy , 아닌데? ㅎㅎ
z = x
# print(y)
# print(z)

# y[0] = 21
# 

print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
z[0] = 21

In [40]:
y

array([[21, 21, 21],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [50]:
arr = np.arange(12).reshape(4,3)
print(arr)
row_mean = arr.mean(axis=1).reshape(4,1)
print(row_mean)
k = arr-row_mean
print(k) 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 1.]
 [ 4.]
 [ 7.]
 [10.]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 선형회귀

In [51]:
#data만 주고 너가 찾아라 이게 머신러닝 프로그램 방식 -> data driven 방식

In [ ]:
#카테고리(binary, one-hot)를 분류할때 쓰는 cost function 은 cross-entropy

In [53]:
# 좋은 cost function 은 convex 하다 그래야 학습이 가능하다

In [54]:
# 경사하강법 알고리즘 학습 함 w = w- a(learning rate)*미분값

In [55]:
# formal definition : 수식으로 보여줬음

In [ ]:
# global minimum, local minimum에 빠지지 않도록 체크해봐야함 (learning rate를 크게 잡아서 튕겨본다던가)

In [66]:
# x_train = [1,2,3]
# y_train = [11,20,29]
# # w = 9, b = 2

#초기화
W = tf.Variable(tf.random_normal([1]), name = 'weight') #variable은 초기화를 해줘야한다 항상
b = tf.Variable(tf.random_normal([1]), name = 'bias')


X = tf.placeholder(tf.float32, shape=[None]) #shape None이기 때문에 n개가 들어올 수 있다 3,4,5 모두가능
Y = tf.placeholder(tf.float32, shape=[None])

#기준
hypothesis = X *W + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

#방식
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

In [67]:
# 위에는 그냥 빌드 단계, 아무것도 실행되는게 없다

In [71]:
sess = tf.Session()
sess.run(tf.global_variables_initializer()) #내가보고있는 그래프의 베리어블을 초기화한다

for step in range(5000):
    i,c,w,k = sess.run([train, cost, W, b], feed_dict = {X:[1,2,3], Y:[9,18,27]})
    if step %100==0:
        print('Step : ',step, 'Cost:',c,
             'W : ', w,
             'b :', k )

i:  None Step :  0 Cost: 385.62064 W :  [1.1975031] b : [-0.6549685]
i:  None Step :  100 Cost: 0.48235464 W :  [8.195248] b : [1.8292482]
i:  None Step :  200 Cost: 0.29806635 W :  [8.367432] b : [1.4379756]
i:  None Step :  300 Cost: 0.1841867 W :  [8.502744] b : [1.1303793]
i:  None Step :  400 Cost: 0.1138162 W :  [8.609112] b : [0.88858074]
i:  None Step :  500 Cost: 0.070330806 W :  [8.692727] b : [0.698504]
i:  None Step :  600 Cost: 0.043460343 W :  [8.758455] b : [0.54908705]
i:  None Step :  700 Cost: 0.02685599 W :  [8.810123] b : [0.43163306]
i:  None Step :  800 Cost: 0.01659535 W :  [8.850741] b : [0.33930317]
i:  None Step :  900 Cost: 0.010254906 W :  [8.8826685] b : [0.26672247]
i:  None Step :  1000 Cost: 0.006336871 W :  [8.907766] b : [0.20966819]
i:  None Step :  1100 Cost: 0.0039158086 W :  [8.927497] b : [0.16481827]
i:  None Step :  1200 Cost: 0.0024197097 W :  [8.943006] b : [0.12956178]
i:  None Step :  1300 Cost: 0.001495194 W :  [8.955197] b : [0.10184643]
i

# gradient decent 직접 구현

In [74]:

W = tf.Variable(tf.random_normal([1]), name = 'weight') #variable은 초기화를 해줘야한다 항상
b = tf.Variable(tf.random_normal([1]), name = 'bias')


X = tf.placeholder(tf.float32, shape=[None]) #shape None이기 때문에 n개가 들어올 수 있다 3,4,5 모두가능
Y = tf.placeholder(tf.float32, shape=[None])

hypothesis = X *W + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

learning_rate = 0.01
gradient = tf.reduce_mean((W*X-Y)*X)
descent = W-learning_rate*gradient
update = W.assign(descent) #노드개념이기 때문에 업데이트하기위해선 assign을 시켜줘야한다

# if gradient > 1000 : # 컨디션 정해줄때 주관적으로 만들어 줄 수 있다.
#     break; 

train = optimizer.minimize(cost)

In [75]:
sess = tf.Session()
sess.run(tf.global_variables_initializer()) #내가보고있는 그래프의 베리어블을 초기화한다

for step in range(5000):
    i,c,w,k = sess.run([train, cost, W, b], feed_dict = {X:[1,2,3], Y:[9,18,27]})
    if step %100==0:
        print('Step : ',step, 'Cost:',c,
             'W : ', w,
             'b :', k )

Step :  0 Cost: 281.73148 W :  [1.4261694] b : [1.5482081]
Step :  100 Cost: 1.4891258 W :  [7.5860624] b : [3.2140906]
Step :  200 Cost: 0.9201884 W :  [7.888551] b : [2.5265837]
Step :  300 Cost: 0.56862205 W :  [8.1263] b : [1.9861256]
Step :  400 Cost: 0.35137355 W :  [8.313192] b : [1.5612756]
Step :  500 Cost: 0.21712725 W :  [8.460106] b : [1.2273045]
Step :  600 Cost: 0.13417172 W :  [8.575594] b : [0.9647746]
Step :  700 Cost: 0.082910344 W :  [8.666377] b : [0.7584014]
Step :  800 Cost: 0.05123371 W :  [8.737742] b : [0.5961734]
Step :  900 Cost: 0.03165931 W :  [8.793841] b : [0.46864694]
Step :  1000 Cost: 0.019563748 W :  [8.83794] b : [0.3684004]
Step :  1100 Cost: 0.012088862 W :  [8.872607] b : [0.28959414]
Step :  1200 Cost: 0.007470291 W :  [8.8998575] b : [0.22764722]
Step :  1300 Cost: 0.00461626 W :  [8.921278] b : [0.17895187]
Step :  1400 Cost: 0.0028525216 W :  [8.938118] b : [0.14067209]
Step :  1500 Cost: 0.0017626513 W :  [8.951355] b : [0.11058132]
Step :  1

In [ ]:
# 텐서플로에서 wx 라고해서 w를 먼저할순 없다 행렬곱 형태를 생각하면 됌
#gpu는 매트릭스곱에 강함, 행렬연산에 강하다
# 짧고, 빠르고, gpu 때문에 행렬곱으로 나타낸다

In [ ]:
# W * X = ELEMENT WISE (각 원소들끼리 곱하는 방식)
# MATMUL(X,W) # 무조건 X가 먼저와야한다

In [77]:
x1_data = [10., 12., 15., 16., 85.]
x2_data = [13., 19., 22., 84., 24.]
x3_data = [15., 18., 244., 34., 64.]
y_data = [152., 241., 214., 142.,899.]

#데이터를 받는건 constant 랑 placeholder 일반적으로 placeholder 씀
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = w3 = tf.Variable(tf.random_normal([1]), name = 'bias')

hypythesis = x1 * w1 + x2 * w2 + x3 * w3 +b #나중에 길어지면 메트릭스 아니면 못씀
cost = tf.reduce_mean(tf.square(hypothesis-Y))
optimizer - tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

TypeError: unsupported operand type(s) for -: 'GradientDescentOptimizer' and 'GradientDescentOptimizer'

In [ ]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2000):
    const_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict = {x1 :x_data, x2: x2_data, x3:x3_data, Y:y_data})
    if step % 100 ==0:
        print()